open Util

module HTm = Hashcons.Make(Tm_rep)
module PProp = Hashcons.Make(Prop_rep.PPropRep)
module NProp = Hashcons.Make(Prop_rep.NPropRep)
module HProof = Hashcons.Make (Proof_rep)

module type T =
sig
  type tm_t = HTm.t
  val tm_table : tm_t

  type pprop_t = PProp.t
  val pprop_table : pprop_t

  type nprop_t = NProp.t
  val nprop_table : nprop_t

  type proof_t = HProof.t
  val proof_table : proof_t

  type sym_t = (int, (string * int)) Hashtbl.t
  val sym_table : sym_t
  val gen_sym : string -> int     (* creates a new symbol or returns and existing one *)
  val lookup_sym : int -> string  (* maps a tag generated by gen_sym to the string *)

  val gen_tag : unit -> Top.tag   (* creates a globally unique identifier *) 
end

